global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'orderserviceapi'
    static_configs:
      - targets: ['orderserviceapi:80']

  - job_name: 'paymentserviceapi'
    static_configs:
      - targets: ['paymentserviceapi:80']
