global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dotnet-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'orderservice:80'
          - 'paymentservice:80'